### ISSUE TITLE
Optimize GitHub Actions workflows for better performance and efficiency

### ISSUE THREAD

**Issue by campbell-rehu** [mushfoo/kometa-dashboard#21]
# GitHub Actions Workflow Optimization

## Overview
Current CI/CD workflows can be optimized for better performance, reduced resource usage, and faster feedback loops. Analysis shows potential for ~30% faster CI runs and ~20% faster builds.

## Current State Analysis

**✅ Good practices already in place:**
- NPM cache enabled in test job (`cache: 'npm'`)
- Uses `npm ci` for faster, reliable installs  
- Efficient job parallelization with `docker-build` depending on `test`
- Self-hosted runners for better performance

### Phase 1: Enhanced Caching Strategy
- **Next.js build cache:** Add `~/.next/cache` to speed up builds
- **TypeScript compiler cache:** Cache TS compilation output
- **ESLint cache:** Cache linting results for faster subsequent runs

```yaml
- name: Cache Next.js build
  uses: actions/cache@v4
  with:
    path: ${{ github.workspace }}/.next/cache
    key: nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx') }}
    restore-keys: nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
```

### Phase 2: Job Parallelization
- **Split test job** into parallel jobs: `lint`, `type-check`, `test`, `build`
- **Independent Docker build:** Remove dependency on test job completion
- **Parallel execution** of linting, type-checking, and testing

### Phase 3: Conditional Execution
- **Path filters:** Skip Docker build for documentation-only changes
- **Smart triggers:** Skip tests for non-code changes
- **Selective runs:** Only run relevant jobs based on changed files

```yaml
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
```

### Phase 4: Performance Enhancements
- **Job timeouts:** Add 15min timeout for test jobs, 10min for Docker
- **Action updates:** Update to latest action versions
- **Build artifacts:** Upload test results and build artifacts for debugging
- **Docker optimization:** Multi-stage builds and layer caching

## Expected Benefits

| Optimization | Expected Improvement |
|--------------|---------------------|
| Parallel jobs | ~30% faster CI runs |
| Enhanced caching | ~20% faster builds |
| Conditional execution | ~50% fewer unnecessary runs |
| Timeouts | Better resource management |
| Artifacts | Improved debugging |

### Phase 1: Enhanced Caching
- [ ] Add Next.js build cache
- [ ] Add TypeScript compiler cache  
- [ ] Add ESLint cache directory
- [ ] Test cache effectiveness

### Phase 2: Job Parallelization  
- [ ] Split test job into: lint, type-check, test, build
- [ ] Make Docker build independent
- [ ] Configure proper job dependencies
- [ ] Test parallel execution

### Phase 3: Conditional Execution
- [ ] Add path filters for docs-only changes
- [ ] Skip Docker for non-deployment changes
- [ ] Configure smart triggers
- [ ] Test conditional logic

### Phase 4: Performance Enhancements
- [ ] Add job timeouts
- [ ] Update action versions
- [ ] Add build artifact uploads
- [ ] Optimize Docker builds
- [ ] Performance testing

## Acceptance Criteria

- [ ] CI run time reduced by at least 25%
- [ ] Build time reduced by at least 15%
- [ ] Documentation changes don't trigger full CI
- [ ] All existing functionality preserved
- [ ] No breaking changes to workflow behavior
- [ ] Proper error handling and fallbacks

## Technical Requirements

- Maintain compatibility with self-hosted runners
- Preserve current security practices
- Ensure reliable caching mechanisms
- Maintain comprehensive test coverage
- Keep workflow maintainable and readable
